# paste your YAML workflow file here and remove sensitive data
      - name: Set up QEMU
        if: steps.needs-build.outputs.result == 'true'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
